// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220005619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyApi.Modals.Asset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasColumnType("text");

                    b.Property<int>("AssetCgId")
                        .HasColumnType("integer");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CategoryAssetCgId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssetId");

                    b.HasIndex("CategoryAssetCgId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("MyApi.Modals.AssetCategory", b =>
                {
                    b.Property<int>("AssetCgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssetCgId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AssetCgId");

                    b.ToTable("AssetCategories");
                });

            modelBuilder.Entity("MyApi.Modals.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MyApi.Modals.Notification", b =>
                {
                    b.Property<int>("NotifiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotifiId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotifiId");

                    b.HasIndex("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MyApi.Modals.RepairCost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CostId"));

                    b.Property<int>("CostAmount")
                        .HasColumnType("integer");

                    b.Property<string>("CostName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CostTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.HasKey("CostId");

                    b.HasIndex("ReportId");

                    b.ToTable("RepairCosts");
                });

            modelBuilder.Entity("MyApi.Modals.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageAfter")
                        .HasColumnType("text");

                    b.Property<string>("ImageBefore")
                        .HasColumnType("text");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("ProgressLog")
                        .HasColumnType("text");

                    b.Property<int>("ReportOwner")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportTechnician")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReportId");

                    b.HasIndex("AssetId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReportOwner");

                    b.HasIndex("ReportTechnician");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("MyApi.Modals.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserFullname")
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPhone")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyApi.Modals.Asset", b =>
                {
                    b.HasOne("MyApi.Modals.AssetCategory", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryAssetCgId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyApi.Modals.Notification", b =>
                {
                    b.HasOne("MyApi.Modals.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId");

                    b.HasOne("MyApi.Modals.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApi.Modals.RepairCost", b =>
                {
                    b.HasOne("MyApi.Modals.Report", "Report")
                        .WithMany("RepairCosts")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("MyApi.Modals.Report", b =>
                {
                    b.HasOne("MyApi.Modals.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Modals.Location", "Location")
                        .WithMany("Reports")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Modals.User", "Owner")
                        .WithMany("Reports")
                        .HasForeignKey("ReportOwner")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApi.Modals.User", "Technician")
                        .WithMany()
                        .HasForeignKey("ReportTechnician")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("Location");

                    b.Navigation("Owner");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("MyApi.Modals.AssetCategory", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("MyApi.Modals.Location", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("MyApi.Modals.Report", b =>
                {
                    b.Navigation("RepairCosts");
                });

            modelBuilder.Entity("MyApi.Modals.User", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
